[package]
name = "rustlib"
version = "0.1.0"

[lib]
name = "rustlib"
crate-type = ["staticlib","rlib"]

[dependencies.rustr]
path = "../../../../../../"
features = ["date", "engine", "random", "logging","ty_nalgebra", "ty_num"]

[dependencies]
nalgebra = "0.5.1"
